export default {
  SIGN_IN: 'Sign In',
  SIGN_UP: 'Sign Up',
  SUBMIT: 'Submit',
  SIGN_OUT: 'Sign Out',
  SEARCH_MOVIE: 'Search',
  CONFIRM: 'Confirm',
  CANCEL: 'Cancel',
  SEARCH_MOVIE_PLACEHOLDER: 'Enter movie title',
  AUTHENIFICATION: 'Authenification',
  YOUR_EMAIL: 'Your email',
  YOUR_PASSWORD: 'Your password',
  CREATE_AN_ACCOUNT: 'Create an Account',
  CONNECT_WITH: 'or connect with',
  TOGGLE_THEME: 'Change theme',
  TOGGLE_LANGUAGE: 'Change language',
  MOVIE_INFO: 'Movie info',
  HOME: 'Home',
  FAVOURITES: 'Favourites',
  WATCH_LATER: 'Watch later',
  WATCHED: 'Watched',
  GENRE: 'Genre',
  CAST: 'Cast',
  DIRECTOR: 'Director',
  COUNTRY: 'Country',
  DURATION: 'Duration',
  RELEASE: 'Release',
  RATING: 'Rating',
  CLOSE: 'Close',
  SORT_MOVIES: 'Sort',
  SORT_BY_TITLE_A_Z: 'Title A-Z',
  SORT_BY_TITLE_Z_A: 'Title Z-A',
  SORT_BY_YEAR_ASC: 'Year ↑',
  SORT_BY_YEAR_DSC: 'Year ↓',
  ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_LIST:
    'Are you sure you want to delete this list?',
  EDIT_LIST: 'Edit list',
  SAVE_CHANGES: 'Save changes',
  DELETE_LIST: 'Delete list',
  NEW_LIST: 'New list',
  ADD: 'Add',
  EXPAND: 'Expand',
  COLLAPSE: 'Collapse',
  WARNING: 'Warning',
};
