const languages = [
  { value: 'en', label: 'EN' },
  { value: 'ua', label: 'UA' },
];

const dic = {
  en: {
    SIGN_IN: 'Sign In',
    SIGN_UP: 'Sign Up',
    SIGN_OUT: 'Sign Out',
    SEARCH_MOVIE: 'Search',
    CONFIRM: 'Confirm',
    CANCEL: 'Cancel',
    SEARCH_MOVIE_PLACEHOLDER: 'Enter movie title',
    AUTHENIFICATION: 'Authenification',
    YOUR_EMAIL: 'Your email',
    YOUR_PASSWORD: 'Your password',
    CREATE_AN_ACCOUNT: 'Create an Account',
    CONNECT_WITH: 'or connect with',
    TOGGLE_THEME: 'Change theme',
    TOGGLE_LANGUAGE: 'Change language',
    MOVIE_INFO: 'Movie info',
    HOME: 'Home',
    FAVOURITES: 'Favourites',
    WATCH_LATER: 'Watch later',
    WATCHED: 'Watched',
    GENRE: 'Genre',
    CAST: 'Cast',
    DIRECTOR: 'Director',
    COUNTRY: 'Country',
    DURATION: 'Duration',
    RELEASE: 'Release',
    RATING: 'Rating',
    CLOSE: 'Close',
    SORT_MOVIES: 'Sort',
    SORT_BY_TITLE_A_Z: 'Title A-Z',
    SORT_BY_TITLE_Z_A: 'Title Z-A',
    SORT_BY_YEAR_ASC: 'Year ↑',
    SORT_BY_YEAR_DSC: 'Year ↓',
    ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_LIST:
      'Are you sure you want to delete this list?',
    EDIT_LIST: 'Edit list',
    SAVE_CHANGES: 'Save changes',
    DELETE_LIST: 'Delete list',
    NEW_LIST: 'New list',
    ADD: 'Add',
    EXPAND: 'Expand',
    COLLAPSE: 'Collapse',
    WARNING: 'Warning',
  },
  ua: {
    SIGN_IN: 'Увійти',
    SIGN_UP: 'Зареєструватись',
    SIGN_OUT: 'Вийти',
    SEARCH_MOVIE: 'Шукати',
    SEARCH_MOVIE_PLACEHOLDER: 'Введіть назву фільма',
    AUTHENIFICATION: 'Аутеніфікація',
    CONFIRM: 'Підтвердити',
    CANCEL: 'Скасувати',
    YOUR_EMAIL: 'Ваша пошта',
    YOUR_PASSWORD: 'Ваш пароль',
    CREATE_AN_ACCOUNT: 'Створити обліковий запис',
    CONNECT_WITH: 'або увійти за допомогою',
    TOGGLE_THEME: 'Змінити тему',
    TOGGLE_LANGUAGE: 'Змінити мову',
    MOVIE_INFO: 'Інформація про фільм',
    HOME: 'Головна',
    FAVOURITES: 'Улюблене',
    WATCH_LATER: 'Дивитись пізніше',
    WATCHED: 'Переглянуте',
    GENRE: 'Жанр',
    CAST: 'У ролях',
    DIRECTOR: 'Режисер',
    COUNTRY: 'Країна',
    DURATION: 'Тривалість',
    RELEASE: 'Рік',
    RATING: 'Рейтинг',
    CLOSE: 'Закрити',
    SORT_MOVIES: 'Сортувати',
    SORT_BY_TITLE_A_Z: 'Назва А-Я',
    SORT_BY_TITLE_Z_A: 'Назва Я-А',
    SORT_BY_YEAR_ASC: 'Рік ↑',
    SORT_BY_YEAR_DSC: 'Рік ↓',
    ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_LIST:
      'Ви дійсно хочете видалити цей список?',
    EDIT_LIST: 'Редагувати',
    SAVE_CHANGES: 'Зберегти зміни',
    DELETE_LIST: 'Видалити список',
    NEW_LIST: 'Новий список',
    ADD: 'Додати',
    EXPAND: 'Показати',
    COLLAPSE: 'Сховати',
    WARNING: 'Попередження',
  },
};

export { dic, languages };
