export default {
  SIGN_IN: 'Увійти',
  SIGN_UP: 'Зареєструватись',
  SIGN_OUT: 'Вийти',
  SEARCH_MOVIE: 'Шукати',
  SEARCH_MOVIE_PLACEHOLDER: 'Введіть назву фільма',
  AUTHENIFICATION: 'Аутеніфікація',
  CONFIRM: 'Підтвердити',
  CANCEL: 'Скасувати',
  YOUR_EMAIL: 'Ваша пошта',
  YOUR_PASSWORD: 'Ваш пароль',
  CREATE_AN_ACCOUNT: 'Створити обліковий запис',
  CONNECT_WITH: 'або увійти за допомогою',
  TOGGLE_THEME: 'Змінити тему',
  TOGGLE_LANGUAGE: 'Змінити мову',
  MOVIE_INFO: 'Інформація про фільм',
  HOME: 'Головна',
  FAVOURITES: 'Улюблене',
  WATCH_LATER: 'Дивитись пізніше',
  WATCHED: 'Переглянуте',
  GENRE: 'Жанр',
  CAST: 'У ролях',
  DIRECTOR: 'Режисер',
  COUNTRY: 'Країна',
  DURATION: 'Тривалість',
  RELEASE: 'Рік',
  RATING: 'Рейтинг',
  CLOSE: 'Закрити',
  SORT_MOVIES: 'Сортувати',
  SORT_BY_TITLE_A_Z: 'Назва А-Я',
  SORT_BY_TITLE_Z_A: 'Назва Я-А',
  SORT_BY_YEAR_ASC: 'Рік ↑',
  SORT_BY_YEAR_DSC: 'Рік ↓',
  ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_LIST:
    'Ви дійсно хочете видалити цей список?',
  EDIT_LIST: 'Редагувати',
  SAVE_CHANGES: 'Зберегти зміни',
  DELETE_LIST: 'Видалити список',
  NEW_LIST: 'Новий список',
  ADD: 'Додати',
  EXPAND: 'Показати',
  COLLAPSE: 'Сховати',
  WARNING: 'Попередження',
};
